authapp/urls.py
from django.urls import path

from authapp.apps import AuthappConfig
from authapp.views import (CustomLoginView, CustomLogoutView, EditView,
                           RegisterView)

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from config import settings

urlpatterns = [
    path("adminboard/", admin.site.urls),
    path("", RedirectView.as_view(url='home/')),
    path("home/", include('mainapp.urls', namespace='home')),
    path("authapp/", include('authapp.urls', namespace='authapp')),
    path("__debug__/", include("debug_toolbar.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

from mainapp import views
from mainapp.apps import MainappConfig


app_name = MainappConfig.name


urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('news/', views.NewsView.as_view(), name='news'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('targets/', views.TargetsView.as_view(), name='targets'),
    path('history/', views.HistoryView.as_view(), name='history'),

    path('projects_category/', views.ProjectCategoryView.as_view(), name='projects_category'),
    path('allyouneedis/', views.AllYouNeedIsView.as_view(), name='allyouneedis'),
    path('donation/', views.DonationView.as_view(), name='donation'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('yandex/', RedirectView.as_view(url='https://yandex.ru/search/', query_string=True), name='yandex'),
    path('offero/', views.OfferoView.as_view(), name='offero'),
    path('personal_data/', views.PersonalDataView.as_view(), name='personal_data'),
    path('legal/', views.LegalView.as_view(), name='legal'),
    path('partners/', views.PartnersView.as_view(), name='partners'),
    path('give_help/', views.GiveHelpView.as_view(), name='give_help'),
    path('get_help/', views.GetHelpView.as_view(), name='get_help'),
    path('success/', TemplateView.as_view(template_name='mainapp/success.html'), name='success'),
    path('news/<slug:post_slug>/', views.NewsDetailView.as_view(), name='news_post'),
    path('projects_category/<int:pk>/', views.ProjectView.as_view(), name='projects'),
    path('projects_post/<slug:slug>/', views.ProjectDetailView.as_view(), name='projects_post'),
    path('allyouneedis/<slug:slug>/', views.AllYouNeedIsDetailView.as_view(), name='allyouneedis_post'),
    path('report/', views.ReportView.as_view(), name='report'),
    path('vid/', views.VideoListView.as_view(), name='video_list'),
    path('video/<int:pk>/', views.VideoDetailView.as_view(), name='video_detail'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/forms.py
from django import forms
from .models import GiveHelp, GetHelp


# Форма анкеты волонтера
class GiveHelpForm(forms.ModelForm):
    agreement = forms.BooleanField(
        label='Согласие на обработку персональных данных', required=True)

    class Meta:
        model = GiveHelp
        # fields = '__all__'
        fields = ['first_name', 'last_name', 'city',
                  'email', 'phone', 'text_1', 'text_2',
                  'schedule', 'help', 'mobility']

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'volounteerFormWrapper__input'}),
            # 'first_name': forms.label(attrs={'class': 'volounteerFormWrapper__sign'}),
            'last_name': forms.TextInput(attrs={'class': 'volounteerFormWrapper__input'}),
            'city': forms.TextInput(attrs={'class': 'volounteerFormWrapper__input'}),
            'phone': forms.TextInput(attrs={'class': 'volounteerFormWrapper__input', 'placeholder': '+7(___)___-__-__'}),
            'email': forms.TextInput(attrs={'class': 'volounteerFormWrapper__input'}),
            'text_1': forms.Textarea(attrs={'class': 'getHelp_inputTextArea volounteerFormWrapper__textArea', 'rows': 8}),
            'text_2': forms.Textarea(attrs={'class': 'getHelp_inputTextArea volounteerFormWrapper__textArea', 'rows': 8}),
            'schedule': forms.Select(attrs={'class': 'volounteerFormWrapper__input'}),
            'help': forms.Select(attrs={'class': 'volounteerFormWrapper__input'}),
            'mobility': forms.Select(attrs={'class': 'volounteerFormWrapper__input'}),
        }


# Форма запроса на помощь
class GetHelpForm(forms.ModelForm):
    agreement = forms.BooleanField(
        label='Согласие на обработку персональных данных', required=True)

    class Meta:
        model = GetHelp
        # fields = '__all__'
        fields = ['name', 'surname', 'city',
                  'email', 'phone', 'text', ]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'getHelp_input'}),
            'surname': forms.TextInput(attrs={'class': 'getHelp_input'}),
            'city': forms.TextInput(attrs={'class': 'getHelp_input'}),
            'email': forms.TextInput(attrs={'class': 'getHelp_input'}),
            'phone': forms.TextInput(attrs={'class': 'getHelp_input', 'placeholder': '+7(___)___-__-__'}),
            'text': forms.Textarea(attrs={'class': 'getHelp_inputTextArea', 'rows': 10}),
        }

mainapp/views.py
import asyncio
import logging
import os
import random
import re
from collections import defaultdict
import time

import aiohttp
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView
from django.views.generic import TemplateView, View
from .models import ItemVideos
from mainapp.forms import GiveHelpForm, GetHelpForm
from mainapp.models import GiveHelp, GetHelp, News, ProjectCategory, AllYouNeedIs, Partners, Project, Report, \
    ImagesMany


class GiveHelpView(View):
    model = GiveHelp
    form_class = GiveHelpForm

    def get(self, request):
        form = GiveHelpForm()
        return render(request, 'mainapp/give_help.html', {'form': form})

    def post(self, request):
        form = GiveHelpForm(request.POST)
        if form.is_valid():
            # Проверяем, было ли отмечено согласие
            if form.cleaned_data['agreement']:
                form.save()
                return redirect('/home/success/')  # перенаправление на страницу успешного заполнения анкеты
            else:
                # Если согласие не было отмечено, добавляем сообщение об ошибке
                form.add_error('agreement', 'Пожалуйста, подтвердите свое согласие.')
        return render(request, 'mainapp/give_help.html', {'form': form})


# # Контроллер страницы с запросом на помощь
class GetHelpView(View):
    model = GetHelp
    form_class = GetHelpForm

    def get(self, request):
        form = GetHelpForm()
        return render(request, 'mainapp/get_help.html', {'form': form})

    def post(self, request):
        form = GetHelpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/home/success/')  # перенаправление на страницу успешного заполнения анкеты

        return render(request, 'mainapp/get_help.html', {'form': form})


# # Контроллер страницы оферты
class PartnersView(ListView):
    model = Partners
    template_name = 'mainapp/partners.html'
    context_object_name = 'object'
    extra_context = {
        'title': 'Наши партнеры',
    }


logger = logging.getLogger(__name__)


# Контроллер страницы контактов
class ContactsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Cвязаться с нами'
        context['contacts'] = [
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CDF44O-k',
                'city': 'МО, Королёв',
                'phone': '+7 (910)401-40-12',
                'email': 'org@fond-oknovmir.ru',
                'address': 'ул. Фрунзе 12',
                'manager': 'Шаройко Ольга Павловна'
            },
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CDFaQOn3',
                'city': 'МО, Красноармейск',
                'phone': '+7(916)011-81-12',
                'email': 'krasnodobro@mail.ru',
                'address': 'пр. Испытателей 25/2',
                'manager': 'Березикова Ирина Владимировна'
            }, {

                'map': 'https://yandex.ru/map-widget/v1/-/CDFaQD-O',
                'city': 'МО, Подольск',
                'phone': '+7(910)000-78-52',
                'email': 'oknovmir.podolsk@mail.ru',
                'address': 'Адреса пока нет',
                'manager': 'Лебедева Ольга Владимировна'
            }, {

                'map': 'https://yandex.ru/map-widget/v1/-/CDFaQL4l',
                'city': 'МО, Апрелевка',
                'phone': '+7(903)247-47-06',
                'email': 'penzina_ys@mail.ru',
                'address': 'Республиканская ул. 13',
                'manager': 'Пензина Юлия Сергеевна'
            }
        ]

        return context

    # Метод для отправки сообщения через форму обратной связи с фильтрацией на спам
    async def send_feedback_to_email(self, message: str, message_from: int = None) -> None:
        self.message_history = defaultdict(int)
        self.spam_threshold = 10  # Устанавливаем порог для определения спама
        self.spam_interval = 60  # Устанавливаем интервал времени для проверки спама

        current_time = time.time()

        if message in self.message_history and current_time - self.message_history[message] < self.spam_interval:
            print("Spam detected. Message not sent.")
            return

        # Проверяем наличие ссылок в сообщении
        if re.search(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', message):
            print("Links are not allowed. Message not sent.")
            return

        self.message_history[message] = current_time

        TOKEN = os.getenv('TOKEN')
        CHAT_ID = os.getenv('CHAT_ID')
        url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
        params = {
            "chat_id": CHAT_ID,
            "text": message,
            "parse_mode": "HTML"
        }

        async with aiohttp.ClientSession() as session:
            async with session.get(url, params=params) as response:
                if response.status == 200:
                    print("Message sent successfully")
                else:
                    print("Message failed to send")
                    print(await response.text())

    def post(self, *args, **kwargs):
        message_body = self.request.POST.get('message_body')
        asyncio.run(self.send_feedback_to_email(message_body))

        return HttpResponseRedirect(reverse_lazy('mainapp:success'))


# Контроллер страницы новостей
# родитель ListView для удобства работы со страницами, где нужна пагинация
class NewsView(ListView):
    paginate_by = 6
    model = News
    template_name = 'mainapp/news.html'
    context_object_name = 'object'
    extra_context = {
        'title': 'Новости',
    }

    # В --get_queryset-- переопределяется --object_list-- который отображает список новостей
    # фильтруется через менеджер --order_by-- по дате создания и реверсируется
    def get_queryset(self):
        queryset = News.objects.order_by('created_at').reverse()
        return queryset


# Контроллер страницы с новостью
class NewsDetailView(DetailView):
    model = News
    template_name = 'mainapp/news_post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'
    extra_context = {
        'title': 'Новости',
    }

    def get_object(self, queryset=None):
        return get_object_or_404(News, slug=self.kwargs[self.slug_url_kwarg])

    # В get_context_data добавляем  context['image'] фотографии которые сортируються по id через slug
    # slug принадлежит определенной новости которая имеет определенный id
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     item = ImagesMany.objects.filter(news_image=News.objects.filter(slug=self.kwargs[self.slug_url_kwarg]).get())
    #     context['image'] = item
    #     print(context)
    #     return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        news_item = self.get_object()
        context['image'] = ImagesMany.objects.filter(news_image=news_item)
        context['videos'] = news_item.videos.all()  # Передаем связанные видео
        print(context)
        return context


# Контроллер проектов. Родитель ListView для удобства работы со страницами где нужна пагинация
class ProjectCategoryView(ListView):
    # paginate_by = 3
    template_name = 'mainapp/projects_category.html'
    model = ProjectCategory
    # pk_url_kwarg = 'pk'
    context_object_name = 'post'
    extra_context = {
        'title': 'Наши проекты',
    }


# Контроллер страницы с проектами
class ProjectView(ListView):
    paginate_by = 6
    template_name = 'mainapp/projects.html'
    model = Project
    pk_url_kwarg = 'pk'
    context_object_name = 'post'
    extra_context = {
        'title': 'Наши проекты',
    }

    # В get_queryset переопределяется object_list в котором содержится наименование проектов отсортированный по категориям
    def get_queryset(self):
        queryset = Project.objects.filter(category=self.kwargs[self.pk_url_kwarg])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = ProjectCategory.objects.filter(id=self.kwargs[self.pk_url_kwarg]).get()
        return context


# Функция вывода случайного проекта
def get_projects():
    projects = Project.objects.all()
    return random.sample(list(projects), k=3)[0]


# Функция вывода случайного подопечного
def get_kids():
    kids = AllYouNeedIs.objects.all()
    return random.sample(list(kids), k=3)[0]


# Функция вывода случайной новости
def get_news():
    news = News.objects.all()
    return random.sample(list(news), k=3)[0]


# Контроллер страницы с проектом
class ProjectDetailView(DetailView):
    model = Project
    template_name = 'mainapp/projects_post.html'
    slug_url_kwarg = 'slug'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        return get_object_or_404(Project, slug=self.kwargs[self.slug_url_kwarg])

    # смотреть 206 строку
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item = ImagesMany.objects.filter(
            projects_image=Project.objects.filter(slug=self.kwargs[self.slug_url_kwarg]).get())
        context['image'] = item
        return context


# Контроллер нуждающихся. Родитель ListView для удобства работы со страницами где нужна пагинация
class AllYouNeedIsView(ListView):
    paginate_by = 6
    # в дальнейшем нужно поставить 9
    template_name = 'mainapp/allyouneedis.html'
    model = AllYouNeedIs
    slug_url_kwarg = 'post'
    context_object_name = 'object'
    extra_context = {
        'title': 'Наши подопечные',
    }

    def get_queryset(self):

mainapp/templates/mainapp/includes/Back.html
<div class="button__back_conteiner">
    <button class="button__back" type="button" onclick="history.back();">Назад</button>
</div>

mainapp/templates/mainapp/includes/feedback_block.html
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ item.get_rating_display }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ item.user }}</h6>
        <p class="card-text">
            {{ item.feedback }}
        </p>
    </div>
</div>

mainapp/templates/mainapp/includes/footer.html
{% load static %}
<footer class="footer">
  <div class="footer__container center">
    <!-- левая часть подвала -->
    <div class="footer__left">
      <div class="footer__logo">
        <a href="{% url 'mainapp:home' %}">
          <img
            class="footer__img"
            src="{% static '/img/icons/logo-footer.png' %}"
            alt="Окно в Мир"
          />
        </a>
        <p class="footer__title">
          МЕЖДУНАРОДНЫЙ БЛАГОТВОРИТЕЛЬНЫЙ ФОНД "ОКНО В МИР"
        </p>
      </div>
      <!-- кнопки "помочь"/"нужна помощь" -->
      <div class="footer__help">
        <a class="footer__buttonHelp" href="{% url 'mainapp:donation' %}"
          >помочь</a
        >
        <a
          class="footer__buttonNeeds"
          href="{% url 'mainapp:get_help' %}"
          onmouseover="onHoverFooter()"
          onmouseout="outHoverFooter()"
          >нужна помощь</a
        >
      </div>
    </div>
    <!-- навигация -->
    <div class="footer__nav">
      <div class="footer__navColumn">
        <a class="footer__text" href="{% url 'mainapp:about' %}">О Нас</a>
        <a class="footer__text" href="{% url 'mainapp:contacts' %}">Контакты</a>
      </div>
      <div class="footer__navColumn">
        <a class="footer__text" href="{% url 'mainapp:news' %}">Новости</a>
        <a class="footer__text" href="{% url 'mainapp:report' %}">Отчеты</a>
      </div>
      <div class="footer__navColumn">
        <a class="footer__text" href="{% url 'mainapp:projects_category' %}"
          >Проекты</a
        >
        <a class="footer__text" href="{% url 'mainapp:allyouneedis' %}"
          >Наши подопечные</a
        >
      </div>
      <div class="footer__navColumn">
        <a class="footer__text" href="{% url 'mainapp:partners' %}">Партнеры</a>
        <a class="footer__text" href="{% url 'mainapp:give_help' %}"
          >Анкета волонтёра</a
        >
      </div>
    </div>
  </div>

  <!-- социальные сети -->
  <div class="footer__social">
    <!-- телега -->
    <a href="https://t.me/oknovmirfond" target="_blank">
      <img class="footer__socialTg" src="{% static '/img/icons/tg.png' %}" alt="tg" />
    </a>
    <!-- vk -->
    <a href="https://vk.com/mbfoknovmir" target="_blank">
      <img class="footer__socialVk" src="{% static '/img/icons/vk.png' %}" alt="vk" />
    </a>
  </div>

  <!-- политика безопасности и связь с разработчиком -->
  <div class="footer__bottom center">
    <a href="{% url 'mainapp:legal' %}" class="footer__bottomText"
      >Политика безопасности</a
    >
    <a href="https://t.me/bossa_matrossa" class="footer__bottomConnect">
      <p class="footer__bottomText">Связь с разработчиком</p>
      <img
        class="footer__icon"
        src="{% static '/img/icons/telegram.png' %}"
        alt="Окно в Мир"
      />
    </a>
  </div>
</footer>

mainapp/templates/mainapp/includes/header.html
{% load static %}

<!-- мобильная шапка -->
<div class="header__mobileMenu header__fixed">
  <div class="header__mobileMenuContainer">
    <!-- лого -->
    <div class="header__mobileMenuLogo">
      <a href="{% url 'mainapp:home' %}">
        <img
          class="header__img"
          src="{% static '/img/icons/logo-header.png' %}"
          alt="Окно в Мир"
        />
      </a>
    </div>

    <div class="header__mobileMenuContent">
      <!-- бургер -->
      <div class="header__burger" onclick="burgerMobile()">
        <img
          class="header__imgBurger"
          src="{% static '/img/icons/burger.png' %}"
          alt="Окно в Мир"
        />
      </div>

      <!-- кнопка "помочь"/"нужна помощь" -->
      <div class="header__mobileHelp">
        <a class="header__mobileButtonHelp" href="{% url 'mainapp:donation' %}"
          >помочь</a
        >
        <a class="header__mobileButtonNeeds" href="{% url 'mainapp:get_help' %}"
          >нужна помощь</a
        >
      </div>
    </div>
  </div>
</div>

<!-- шапка для всех других сустройств -->
<header class="header header__fixed">
  <div class="header__container center">
    <!-- лого -->
    <div class="header__logo">
      <a href="{% url 'mainapp:home' %}">
        <img
          class="header__img"
          src="{% static '/img/icons/logo-header.png' %}"
          alt="Окно в Мир"
        />
      </a>
    </div>

    <!-- навигация -->
    <nav class="header__nav">
      <a class="header__text" href="{% url 'mainapp:about' %}">О НАС</a>
      <a class="header__text" href="{% url 'mainapp:news' %}">НОВОСТИ</a>
      <a class="header__text" href="{% url 'mainapp:projects_category' %}"
        >ПРОЕКТЫ</a
      >
      <a class="header__text" href="{% url 'mainapp:allyouneedis' %}"
        >ПОДОПЕЧНЫЕ</a
      >
      <a class="header__text" href="{% url 'mainapp:partners' %}">ПАРТНЕРЫ</a>
    </nav>

    <!-- кнопка "помочь"/"нужна помощь" -->
    <div class="header__help">
      <a class="header__buttonHelp" href="{% url 'mainapp:donation' %}"
        >помочь</a
      >
      <a
        class="header__buttonNeeds"
        href="{% url 'mainapp:get_help' %}"
        onmouseover="onHover()"
        onmouseout="outHover()"
        >нужна помощь</a
      >
    </div>
  </div>
</header>

mainapp/templates/mainapp/includes/inc_main_menu.html
{% with request.resolver_match.url_name as url_name %}



<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">Профиль

            </a>
            <div class="dropdown-menu" aria-labelledby="ddProfile">
                <a class="dropdown-item" href="{% url 'authapp:edit' %}">Редактировать профиль

                </a>

                <div class="dropdown-divider"></div>
                {% if user.is_staff %}
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Модерация

                    </a>
                {% endif %}
                {% if user.is_superuser %}
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель

                    </a>

                {% endif %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'authapp:logout' %}">Выход

                </a>
            </div>
        </li>
        {% else %}
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'authapp:login' %}">Вход</a>
            </li>
        {% endif %}
         <li class="nav-item ">
                <a class="nav-link" href="{% url 'mainapp:about' %}">О Нас</a>
        </li>
        <li class="nav-item ">
                <a class="nav-link" href="{% url 'mainapp:news' %}">Новости</a>
        </li>
        <li class="nav-item ">
                <a class="nav-link" href="{% url 'mainapp:projects_category' %}">Проекты</a>
        </li>
        <li class="nav-item ">
                <a class="nav-link" href="{% url 'mainapp:allyouneedis' %}">Наши подопечные</a>
        </li>
        <li class="nav-item ">
                <a class="nav-link" href="{% url 'mainapp:partners' %}">Партнеры</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">Волонтеры </a>
            <div class="dropdown-menu" aria-labelledby="ddProfile">
                <a class="dropdown-item" href="{% url 'mainapp:give_help' %}">Стать волонтером</a>
                <a class="dropdown-item" href="{% url 'mainapp:get_help' %}">Попросить о помощи</a>
                <li class="nav-item ">
                <a class="nav-link" href="{% url 'mainapp:donation' %}">Сделать пожертвование</a>
        </li>
        <li class="nav-item ">
                <a class="nav-link" href="{% url 'mainapp:contacts' %}">Контакты</a>
        </li>
    </ul>

            </div>
{% endwith %}

mainapp/templates/mainapp/includes/paginator.html
<!--    # После блока content начинается пагинация на каждой странице сробатывает надо учитывать-->
<!-- # идет проверка о наличии страниц -->
{% if page_obj.has_other_pages %}
<nav class="paginator">
  <!-- #отоброжаем стрелку -->
  {% if page_obj.has_previous %}
  <a href="?page=1" class="paginator__end">&laquo;</a>
  <a href="?page={{ page_obj.previous_page_number }}" class="paginator__left"></a>


  <!-- <a href="?page=1" class="paginator__left"></a>
  <a href="?page={{ page_obj.previous_page_number }}" class="paginator__end">&laquo;</a> -->
  {% endif %} 
  <!--  -->
  {% for p in paginator.page_range %}<!-- цикл  for  переберает страницы -->
  {% if page_obj.number == p %}
  <div class="paginator__textActive">{{ p }}</div>
  <!-- Дальше по документации
            https://docs.djangoproject.com/en/3.1/topics/pagination/ -->
  {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
  <div class="paginator__text">
    <a href="?page={{ p }}" class="paginator__text ">{{ p }}</a>
  </div>
  {% endif %} 
  <!--  -->
  {% endfor %} 
  <!--  -->
  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}" class="paginator__right"></a>
  <a href="?page={{ page_obj.paginator.num_pages }}" class="paginator__end">&raquo;</a>
  {% endif %}
</nav>
{% endif %}

mainapp/templates/mainapp/includes/posts.html
<h1>{{ post.name }}</h1>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-7">
                {% if post.photo %}
            <p><img class="img-header-photo" src="/home{{post.photo.url}}" width="300" height="250"></p>
            {% endif %}
            <p> {{ post.description|linebreaks }}</p>
            <p>{{ post.created_at }}</p>
            </div>
    </div>

mainapp/templates/mainapp/includes/tg_link.html
<!-- <p>Тг <a href="{{ post.tg_link }}" target="_blank"> {{ post.tg_link }}</a></p> -->

{% load static %}

<a class="post__link" href="{{ post.tg_link }}" target="_blank">
  <p>Читайте подробнее в</p>
  <img
    class="post__link_icon"
    src="{% static '/img/icons/tg_post.png' %}"
    alt="vk"
/></a>

mainapp/templates/mainapp/includes/vk.link.html
<!-- <p class="newsPost__link">Читайте подробнее в ВКонтакте:  <a href="{{ post.vk_link }}" target="_blank"> {{ post.vk_link }}</a></p> -->
{% load static %}

<a class="post__link" href="{{ post.vk_link }}" target="_blank">
  <p>Читайте подробнее в</p>
  <img
    class="post__link_icon"
    src="{% static '/img/icons/vk_post.png' %}"
    alt="vk"
/></a>