authapp/urls.py
from django.urls import path

from authapp.apps import AuthappConfig
from authapp.views import (CustomLoginView, CustomLogoutView, EditView,
                           RegisterView)

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from config import settings

urlpatterns = [
    path("adminboard/", admin.site.urls),
    path("", RedirectView.as_view(url='home/')),
    path("home/", include('mainapp.urls', namespace='home')),
    path("authapp/", include('authapp.urls', namespace='authapp')),
    path("__debug__/", include("debug_toolbar.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    telegram_id = models.PositiveIntegerField(verbose_name='ID Телеграм', **NULLABLE)
    email = models.EmailField(blank=True, verbose_name=_("email"), unique=True)
    age = models.PositiveSmallIntegerField(verbose_name=_("age"), **NULLABLE)
    avatar = models.ImageField(upload_to="users", verbose_name=_("avatar"), **NULLABLE)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

authapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'age',
            'avatar'
        )

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise ValidationError('Контент 18+')
        else:
            return age


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'age',
            'avatar'
        )

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise ValidationError('Контент 18+')
        else:
            return age

authapp/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from authapp.forms import CustomUserChangeForm, CustomUserCreationForm
from authapp.models import User


class CustomLoginView(LoginView):
    template_name = 'authapp/login.html'
    extra_context = {
        'title': 'Вход пользователя'
    }


class RegisterView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('authapp:login')


class CustomLogoutView(LogoutView):
    template_name = 'mainapp/index.html'


class EditView(UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = 'authapp/edit.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('authapp:edit')

authapp/templates/authapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Welcome to Z!</title>
</head>
<body>
<div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
    <div class="text-center">
        <p>
            <a href="{% url 'mainapp:home' %}"><img src="{% static 'img/Z.jpg' %}" alt=""></a>
        </p>
        <h2>{{title }}</h2>
        {% block content %}
        {% endblock %}

    </div>
</div>

</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'mainapp/base.html' %}

{% load crispy_forms_tags i18n %}

{% block content %}

    <div class="row justify-content-center my-2">
        <div class="row justify-content-center">
            <div class="col-sm-7 col-md-5 col-lg-4">
                {% if user.avatar %}
                    <img src="{{ user.avatar.url }}" alt="" width="100%">
                {% else %}
                    <img src="{{ DEFAULT_AVATAR_URL }}user004.png" alt="" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type=" submit" class="btn btn-primary btn-block">
            {% translate 'Save' %}
        </button>
    </form>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                $(".toast").toast({delay: 5000});
                $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>
        <input id="id_username" class="form-control" type="text" name="username" placeholder="Имя пользователя"
               required="" autofocus="">
    </p>
    <p>
        <input id="id_password" class="form-control" type="password" name="password" placeholder="Пароль"
               required="">
    </p>
    <p>
        <button type="submit" class="btn btn-primary btn-block">Войти</button>
    </p>
</form>
<div class="row justify-content-between">
        <div class="col">
            <a href="{% url 'authapp:register' %}"><small>Регистрация</small></a>
        </div>
        <div class="col">
            <a href="#"><small>Забыли пароль?</small></a>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/user_form.html
{% extends 'authapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row justify-content-center my-2">
    <div class="col-lg-6">
        {% if user.is_anonymous %}
        <h3>Регистрация нового пользователя</h3>
        {% else %}
        <h3>Редактировать профиль</h3>
        <div class="row justify-content-center">
            <div class="col-sm-7 col-md-5 col-lg-4">
                {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="" width="100%">
                {% else %}
                <img src="{{ DEFAULT_AVATAR_URL }}user003.png" alt="" width="100%">
                {% endif %}
            </div>
        </div>
        {% endif %}
        <form method="post" class="mt-2" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary btn-block">
                {% if user.is_anonymous %}
                Зарегистрироваться
                {% else %}
                Сохранить
                {% endif %}
            </button>
        </form>
    </div>
</div>
{% endblock content %}

--{% block js %}-->
    <script>
        $(document).ready(function () {
            {% if messages %}
                $(".toast").toast({delay: 5000});
                $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}